---
title: A Front-End Developer's Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: liakwee@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://liakwee.github.com
twitter_username: liakwee
github_username: liakwee
markdown: kramdown
highlighter: pygments
exclude:
- node_modules
- gulpfile.js
- package.json
